language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
    - "$HOME/.npm"
services:
  - mongodb
before_script:
  - sleep 15
jobs:
  include:
  - stage: test
    script:
    - npm run test-server
  - stage: deploy-ropsten
    install: true
    if: branch = develop AND type = push
    script:
    - npm i -g now
    - export GIT_REV=`git rev-parse --short HEAD`
    - cd server && npm run deploy-ropsten && npm run alias-ropsten && cd ..
    - cd app && npm run deploy-now-ropsten && npm run alias-ropsten && cd ..
  - stage: deploy
    install: true
    if: tag IS present
    script:
    - npm i -g now
    - export GIT_REV=`git rev-parse --short HEAD`
    - echo 'Deploying to NOW'
    - cd server && npm run deploy && npm run alias && cd ..
    - cd app && npm run deploy-now && npm run alias && cd ..
