module.exports = {
  BOOKING_POC_ADDRESS: process.env.BOOKING_POC_ADDRESS || '0x028C2ed488804A80e8355590575979397403078C',
  WHITELIST: process.env.WHITELIST || '*',
  SERVER_PORT: process.env.SERVER_PORT || 3000,
  STARTING_BLOCK: process.env.STARTING_BLOCK || 3668521,
  MONGODB_URI: process.env.MONGODB_URI,
  MAIL_API_KEY: process.env.MAIL_API_KEY,
  FROM_EMAIL: process.env.FROM_EMAIL,
  OWNER_PRIVATE_KEY: process.env.OWNER_PRIVATE_KEY,
  OWNER_ADDRESS: process.env.OWNER_ADDRESS,
  WEB3_PROVIDER: process.env.WEB3_PROVIDER,
};
