module.exports = {
  BOOKING_POC_ADDRESS: process.env.BOOKING_POC_ADDRESS || '0x028C2ed488804A80e8355590575979397403078C',
  WHITELIST: process.env.WHITELIST || '*',
  SERVER_PORT: process.env.SERVER_PORT || 3000,
  STARTING_BLOCK: process.env.STARTING_BLOCK || 3668521,
  MONGODB_URI: process.env.MONGODB_URI,
  MAILGUN_API_KEY: process.env.MAILGUN_API_KEY,
  MAILGUN_DOMAIN: process.env.MAILGUN_DOMAIN,
  MAILGUN_FROM_EMAIL: process.env.MAILGUN_FROM_EMAIL,
  MAILGUN_TO_EMAIL: process.env.MAILGUN_TO_EMAIL,
  OWNER_PRIVATE_KEY: process.env.OWNER_PRIVATE_KEY,
  OWNER_ADDRESS: process.env.OWNER_ADDRESS,
  WEB3_PROVIDER: process.env.WEB3_PROVIDER,
};
